version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - 1337:3000
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
    - 80:80
    depends_on:
    - backend

  db:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user123
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: task_database

volumes:
  pgdata: